/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import christmasHat from './christmas-hat-01.glb'

export default function ChristmasHat01({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(christmasHat)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[0.37, -0.04, -0.11]}>
          <mesh geometry={nodes.Mesh_0.geometry} material={materials.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/christmas-hat-01.glb')
