/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Goku(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/goku.glb')
  const { actions } = useAnimations(animations, group)
    useEffect(() => {
        console.log('actions', actions);
        actions.situp.play();
    });
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.02, 0.01, 0]} rotation={[0, 0, 3]} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
            castShadow
            scale={[1500, 1500, 1500]}
          geometry={nodes.Mesh_0.geometry}
          material={materials['Scene_-_Root']}
          skeleton={nodes.Mesh_0.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/goku.glb')
