/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Goku02(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/goku-02.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          geometry={nodes['Model001_40_+Outfit1_Bust1Outfit1_Bust1_1_0_0'].geometry}
          material={materials.Model001_Material021mat}
          skeleton={nodes['Model001_40_+Outfit1_Bust1Outfit1_Bust1_1_0_0'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['Model001_40_+Outfit1_Bust2Outfit1_Bust2_1_0_0'].geometry}
          material={materials.Model001_Material003mat}
          skeleton={nodes['Model001_40_+Outfit1_Bust2Outfit1_Bust2_1_0_0'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['Model001_40_+Outfit1_Bust3Outfit1_Bust3_1_0_0'].geometry}
          material={materials.Model001_Material009mat}
          skeleton={nodes['Model001_40_+Outfit1_Bust3Outfit1_Bust3_1_0_0'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['Model001_40_+Outfit1_Bust4Outfit1_Bust4_1_0_0'].geometry}
          material={materials.Model001_Material014mat}
          skeleton={nodes['Model001_40_+Outfit1_Bust4Outfit1_Bust4_1_0_0'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['Model001_40_+Outfit1_Pants1Outfit1_Pants1_1_0_0'].geometry}
          material={materials.Model001_Material002mat}
          skeleton={nodes['Model001_40_+Outfit1_Pants1Outfit1_Pants1_1_0_0'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['Model001_40_+Outfit2_Bust3Outfit2_Bust3_1_0_0'].geometry}
          material={materials.Model001_Material023mat}
          skeleton={nodes['Model001_40_+Outfit2_Bust3Outfit2_Bust3_1_0_0'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['Model001_40_+Outfit2_Bust5Outfit2_Bust5_1_0_0'].geometry}
          material={materials.Model001_Material017mat}
          skeleton={nodes['Model001_40_+Outfit2_Bust5Outfit2_Bust5_1_0_0'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['Model001_40_+Outfit2_Pants2Outfit2_Pants2_1_0_0'].geometry}
          material={materials.Model001_Material011mat}
          skeleton={nodes['Model001_40_+Outfit2_Pants2Outfit2_Pants2_1_0_0'].skeleton}
        />
        <skinnedMesh
          geometry={nodes.Model001_40_Material102_1_0_0.geometry}
          material={materials.Model001_Material020mat}
          skeleton={nodes.Model001_40_Material102_1_0_0.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Model001_40_Material103_1_0_0.geometry}
          material={materials.Model001_Material001mat}
          skeleton={nodes.Model001_40_Material103_1_0_0.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Model001_40_Material104_1_0_0.geometry}
          material={materials.Model001_Material008mat}
          skeleton={nodes.Model001_40_Material104_1_0_0.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Model001_40_Material105_1_0_0.geometry}
          material={materials.Model001_Material013mat}
          skeleton={nodes.Model001_40_Material105_1_0_0.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Model001_40_Material106_1_0_0.geometry}
          material={materials.Model001_Material018mat}
          skeleton={nodes.Model001_40_Material106_1_0_0.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Model001_40_Material107_1_0_0.geometry}
          material={materials.Model001_Material010mat}
          skeleton={nodes.Model001_40_Material107_1_0_0.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Model001_40_Material108_1_0_0.geometry}
          material={materials.Model001_Material025mat}
          skeleton={nodes.Model001_40_Material108_1_0_0.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Model001_40_Material109_1_0_0.geometry}
          material={materials.Model001_Material019mat}
          skeleton={nodes.Model001_40_Material109_1_0_0.skeleton}
        />
        <skinnedMesh
          geometry={nodes['Model001_40_Material25(1)_1_0_0'].geometry}
          material={materials.Model001_Material015mat}
          skeleton={nodes['Model001_40_Material25(1)_1_0_0'].skeleton}
        />
        <skinnedMesh
          geometry={nodes.Model001_40_Material25_1_0_0.geometry}
          material={materials.Model001_Material005mat}
          skeleton={nodes.Model001_40_Material25_1_0_0.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Model001_40_Material87_1_0_0.geometry}
          material={materials.Model001_Material024mat}
          skeleton={nodes.Model001_40_Material87_1_0_0.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Model001_40_Material96_1_0_0.geometry}
          material={materials.Model001_Material022mat}
          skeleton={nodes.Model001_40_Material96_1_0_0.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Model001_40_Material97_1_0_0.geometry}
          material={materials.Model001_Material004mat}
          skeleton={nodes.Model001_40_Material97_1_0_0.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/goku-02.glb')
