/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Naruto(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/naruto.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions[props.narutoAction].reset().fadeIn(0.5).play()
    return () => actions[props.narutoAction].fadeOut(0.5)
  }, [actions, props.narutoAction]);
  console.log('naruto prop:', props.narutoAction)

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          geometry={nodes.Object_10.geometry}
          material={nodes.Object_10.material}
          skeleton={nodes.Object_10.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_11.geometry}
          material={nodes.Object_11.material}
          skeleton={nodes.Object_11.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_12.geometry}
          material={materials.Model001_Material014}
          skeleton={nodes.Object_12.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_13.geometry}
          material={materials.Model001_Material015}
          skeleton={nodes.Object_13.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_14.geometry}
          material={nodes.Object_14.material}
          skeleton={nodes.Object_14.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_15.geometry}
          material={materials.Model001_Material017}
          skeleton={nodes.Object_15.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_3.geometry}
          material={nodes.Object_3.material}
          skeleton={nodes.Object_3.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_4.geometry}
          material={materials.Model001_Material005}
          skeleton={nodes.Object_4.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_5.geometry}
          material={materials.Model001_Material006}
          skeleton={nodes.Object_5.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_6.geometry}
          material={nodes.Object_6.material}
          skeleton={nodes.Object_6.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_7.geometry}
          material={nodes.Object_7.material}
          skeleton={nodes.Object_7.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_8.geometry}
          material={nodes.Object_8.material}
          skeleton={nodes.Object_8.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_9.geometry}
          material={nodes.Object_9.material}
          skeleton={nodes.Object_9.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/naruto.glb')
